name: Java 23 Build

on:
  push:
    branches:
      - main

env:
  DOCKER_IMAGE_NAME: spring-rag
  DOCKER_REGISTRY_URL: ghcr.io
  DOCKER_USERNAME: teroaz

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '23'
          cache: gradle

      - name: Make Gradlew executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew clean build

  #  test:
  #    runs-on: ubuntu-latest
  #    needs: build
  #    steps:
  #      - name: Checkout code
  #        uses: actions/checkout@v3
  #
  #      - name: Set up JDK 23
  #        uses: actions/setup-java@v3
  #        with:
  #          distribution: 'temurin'
  #          java-version: '23'
  #          cache: gradle
  #
  #      - name: Run tests
  #        run: ./gradlew test
  #
  #  package:
  #    runs-on: ubuntu-latest
  #    needs: build
  #    steps:
  #      - name: Checkout code
  #        uses: actions/checkout@v3
  #
  #      - name: Set up JDK 23
  #        uses: actions/setup-java@v3
  #        with:
  #          distribution: 'temurin'
  #          java-version: '23'
  #          cache: gradle
  #
  #      - name: Jar with Gradle
  #        run: ./gradlew jar

  docker:
    runs-on: ubuntu-latest
#    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '23'
          cache: gradle

      - name: Package with Gradle
        run: ./gradlew bootJar

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY_URL }}
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ env.DOCKER_REGISTRY_URL }}/${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}